tools:
  # we want to use a pinned version of binpack to manage the toolchain (so binpack manages itself!)
  - name: binpack
    version:
      want: v0.8.0
    method: github-release
    with:
      repo: khulnasoft/binpack

  # used for linting
  - name: golangci-lint
    version:
      want: v1.61.0
    method: github-release
    with:
      repo: golangci/golangci-lint

  # used for organizing imports during static analysis
  - name: gosimports
    version:
      want: v0.3.8
    method: github-release
    with:
      repo: rinchsan/gosimports

  # used during static analysis for license compliance
  - name: golicenses
    version:
      want: v0.4.0
    method: github-release
    with:
      repo: khulnasoft/go-licenses

  # used for running all local and CI tasks
  - name: task
    version:
      want: v3.39.0
    method: github-release
    with:
      repo: go-task/task
